# docker-compose.yml
# version: "3.9"

services:
  elysia:
    image: "oven/bun:latest"
    container_name: "elysia_unity"
    restart: "unless-stopped"
    networks:
      - dev-proxy
      - mongodbnet
    # override default entrypoint allows us to do `bun install` before serving
    entrypoint: []
    # execute bun install before we start the dev server in watch mode
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    # setup a host mounted volume to sync changes to the container
    volumes:
      - "./app:/home/bun/app"
    # expose the right ports
    # ports: ["7777:3000"]
    labels:
      - "traefik.http.routers.elysia-http.entrypoints=web"
      - "traefik.http.routers.elysia-http.rule=Host(`elysia.docker.localhost`)"
      - "traefik.http.services.elysia.loadbalancer.server.port=3000"
      # - "traefik.http.routers.elysia-http.middlewares=elysia-https"
      # - "traefik.http.middlewares.elysia-https.redirectscheme.scheme=https"
      # - "traefik.http.routers.elysia.entrypoints=websecure"
      # - "traefik.http.routers.elysia.rule=Host(`elysia.docker.localhost`)"
      # - "traefik.http.routers.elysia.tls=true"
      - "traefik.docker.network=dev-proxy"

  mongodb:
    image: bitnami/mongodb:latest
    container_name: "mongo_unity"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - "./data:/data/db"
      # - type: volume
      #   source: ./data
      #   target: /data/db
    labels:
      - "traefik.http.routers.mongo-http.entrypoints=web"
      - "traefik.http.routers.mongo-http.rule=Host(`mongo.docker.localhost`)"
      - "traefik.http.services.mongo.loadbalancer.server.port=27017"
      # - "traefik.http.routers.mongo-http.middlewares=mongo-https"
      # - "traefik.http.middlewares.mongo-https.redirectscheme.scheme=https"
      # - "traefik.http.routers.mongo.entrypoints=websecure"
      # - "traefik.http.routers.mongo.rule=Host(`mongo.docker.localhost`)"
      # - "traefik.http.routers.mongo.tls=true"
      - "traefik.docker.network=dev-proxy"
    networks:
      - mongodbnet

networks:
  dev-proxy:
    external: true
  mongodbnet:
# volumes:
#   data:
