# docker-compose.yml
# version: "3.9"

services:
  elysia:
    image: "oven/bun:latest"
    container_name: "elysia_unity"
    restart: "unless-stopped"
    networks:
      - dev-proxy
      - mongodbnet
    # override default entrypoint allows us to do `bun install` before serving
    entrypoint: []
    # execute bun install before we start the dev server in watch mode
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    # setup a host mounted volume to sync changes to the container
    volumes:
      - "./app:/home/bun/app"
    # expose the right ports
    # ports: ["7777:3000"]
    labels:
      - "traefik.http.routers.elysia-http.entrypoints=web"
      - "traefik.http.routers.elysia-http.rule=Host(`elysia.docker.localhost`)"
      - "traefik.http.services.elysia.loadbalancer.server.port=3000"
      # - "traefik.http.routers.elysia-http.middlewares=elysia-https"
      # - "traefik.http.middlewares.elysia-https.redirectscheme.scheme=https"
      # - "traefik.http.routers.elysia.entrypoints=websecure"
      # - "traefik.http.routers.elysia.rule=Host(`elysia.docker.localhost`)"
      # - "traefik.http.routers.elysia.tls=true"
      - "traefik.docker.network=dev-proxy"

  postgres:

networks:
  dev-proxy:
    external: true
  mongodbnet:
# volumes:
#   data:
